app/views/Web.py
# -*- coding:utf-8 -*-
import hashlib
from flask import current_app, render_template, request, redirect, url_for, Blueprint, abort
import flask_login
from ..models.dbORM import Color,Space
from app import db, login_manager
web = Blueprint('web', __name__)


@web.route('/')
def protected():
    return "hello world"


@web.route('/birthcolor')
def birthcolorList():
    colors = Color.query.all()
    return render_template("game/colorList.html", colors=colors)


@web.route('/birthcolor/<id>')
def birthcolor(id):
    color = Color.query.filter_by(id=id).first()
    if color:
        return render_template("game/color.html", color=color)
    else:
        abort(404)

@web.route('/space')
def spaceSearch():
    return render_template("game/spacesearch.html")


@web.route('/space/<id>')
def space(id):
    space = Space.query.filter_by(id=id).first()
    if space:
        return render_template("game/space.html", space=space)
    else:
        abort(404)

@web.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

app/views/game.py
# -*- coding:utf-8 -*-
import random

from  flask import Blueprint, request, render_template, make_response

game = Blueprint('game', __name__)


@game.route('/thanos')
def Thanos():
    if 'status' in request.cookies:
        status = request.cookies.get('status')
    else:
        status = random.randint(0, 1)
    if 'count' in request.cookies:
        count = request.cookies.get('count')
    else:
        count = 0
    count = 1 + count
    if status==1:
        if count<3:
            resp = make_response(render_template("game/thanos.html",msg=u"很不幸，你被灭霸干掉了"))
        else:
            resp = make_response(render_template("game/thanos.html",msg=u"不要做无谓的努力了，你的死是为了更好的未来"))
    else:
        if count < 3:
            resp = make_response(render_template("game/thanos.html",msg=u"你从灭霸的手中侥幸逃脱了，可以看到明天的朝阳"))
        else:
            resp = make_response(render_template("game/thanos.html",msg=u"怎么，活着不开心，非要皮%d下？"%(count-2)))

    resp.set_cookie('status', status)
    resp.set_cookie('count', count)
    return resp

app/templates/game/GufengWeb.html
<!DOCTYPE html>
<html>
<head>
    <title>古风生成器</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!--Import Google Icon Font-->
    <link href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet">
    <!--Import materialize.css-->
    <link href="https://cdn.bootcss.com/materialize/0.100.2/css/materialize.min.css" rel="stylesheet">
    {#    <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}">#}
    <style type="text/css">
        #c1 {
            text-align: center;
            padding-top: 15px;
        }
        #date{
            width: 110px;
        }
    </style>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
     <div class="row" style="padding-top: 100px">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text" style="white-space: pre-line;" id="content">

            </div>
            <div class="card-action">
              <a class="waves-effect waves-light btn  orange darken-1" href="#"  id="submit">古风</a>
                <a class="waves-effect waves-light btn  orange darken-1" href="#" data-clipboard-target="#content"  id="copy">复制</a>
            </div>
          </div>
        </div>
      </div>




</body>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/clipboard.js/2.0.4/clipboard.js"></script>
<script src="https://cdn.bootcss.com/materialize/0.100.2/js/materialize.min.js"></script>
<script>
    function getData(order_by) {

        $.ajax({
            url: '/game/api/gufeng',
            dataType: "json",
            contentType: "application/json",
            async: false,
            success: function (data) {
                if (data["result"]) {

                    $("#content").html(data["result"]);

                }
                else {

                }

            }

        })
    }
    var clipboard = new ClipboardJS('#copy');
    clipboard.on('success', function(e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);
    alert("复制成功");
    e.clearSelection();//清除复制后文字的选中状态
    });

    $("#submit").click(function () {
        getData();
    });
</script>
</html>

app/templates/game/color.html
{% extends "base.html" %}
{% block css %}
<title>生日色彩</title>
{% endblock %}
{% block content %}
<div style="height: 100%;width: 100%;background-color: {{ color.color }};color: {{ color.fontcolor }};
padding-top: 60px;padding-left: 10px;padding-right: 10px;">
    <div style="width: 100%;text-align: left">
        <h2>{{ color.id|noZeroBefore }}</h2>
        <h4>{{ color.cname }}</h4>
        <h5>特征：{{ color.cprop1 }}</h5>
        <h5>花语：{{ color.cprop2 }}</h5>
    </div>

    <!-- Modal Trigger -->
</div>
<div style="width: 100%;bottom: 15px;position: absolute;text-align: center">
    <a href="{{ url_for('web.space',id=color.id) }}" style="color: black;" class="modal-trigger">
        <p style="color: {{ color.fontcolor }}">生日那天的宇宙</p>
    </a>
    <a href="#modal1" style="color: black;" class="modal-trigger">
        <p style="color: {{ color.fontcolor }}">查看原文</p>
    </a>
    <a href="http://birthday-color.cafein.jp/html/{{ color.id }}.html" style="color: black;">
        <p style="color: {{ color.fontcolor }}">访问原网站</p>
    </a>
    <a href="{{ url_for('web.birthcolorList') }}" style="color: black;">
        <p style="color: {{ color.fontcolor }}">回首页</p>
    </a>

</div>
  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>日文原文</h4>
      <p>{{ color.jname1 }}</p>
      <p>{{ color.jname2 }}</p>
      <p>特徴：{{ color.jprop1 }}</p>
      <p>色言葉：{{ color.jprop2 }}</p>
    </div>
  </div>
{% endblock %}
{% block script %}
<script>
    window.onload = function () {
        $("html").css("height", "100%");
        $("body").css("height", "100%");
        $('.modal').modal();
    }
</script>
{% endblock %}

app/templates/game/colorList.html
{% extends "base.html" %}
{% block css %}
<title>生日色彩</title>
{% endblock %}
{% block content %}
<a href="http://birthday-color.cafein.jp/">
  <div class="card teal lighten-4" style="margin-top: 0;padding: 5px">
    <div class="card-content black-text" style="padding: 12px">
      <p>
        创意&数据来源于
      </p>
      <p>
        http://birthday-color.cafein.jp/
      </p>
      <p>
        点击访问原网站
      </p>
      <p>
        汉化目前为机翻，逐渐完善中
      </p>
    </div>
  </div>
</a>
<div class="row">
  {% for c in colors %}
  <a href="{{ url_for('web.birthcolor',id=c.id) }}">
    <div class="col s12 m4">

      <div class="card" style="background-color: {{c.color}};height: 160px;">

        {% if c.fontcolor=="white" %}
        <div class="card-content white-text">
          {% else %}
          <div class="card-content black-text">
            {%  endif %}
            <span class="card-title">{{ c.id|noZeroBefore }}</span>
            <p>{{ c.cprop1 }}</p>
            <p>{{ c.cprop2 }}</p>
          </div>
        </div>
      </div>
  </a>


  {% endfor %}
</div>
<div class="fixed-action-btn">
  <a class="btn-floating btn-large blue lighten-3 modal-trigger" href="#modal1">
    <i class="large material-icons">search</i>
  </a>
</div>
<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <div class="input-field">
      <input id="date" type="number" class="validate">
      <label for="date">输入日期</label>
      <span class="helper-text" data-error="wrong" data-success="right">如：0614</span>
    </div>
  </div>
  <div class="modal-footer">
    <a class="modal-close waves-effect waves-green btn-flat" id="submit">确认</a>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function () {
    //$('.fixed-action-btn').floatingActionButton();
    $('.modal').modal();
    $("#submit").click(function () {
      var val = $("#date").val();
      window.location.href = "birthcolor/" + val;
    })
  });
</script>
{% endblock %}

app/templates/game/liuzi.html
<!DOCTYPE html>
<html>
<head>
    <title>刘子の幸福研途</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!--Import Google Icon Font-->
    <link href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet">
    <!--Import materialize.css-->
    <link href="https://cdn.bootcss.com/materialize/0.100.2/css/materialize.min.css" rel="stylesheet">
    {#    <link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}">#}
    <style type="text/css">
        #c1 {
            text-align: center;
            padding-top: 15px;
        }
        #date{
            width: 110px;
        }
    </style>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
<div class="row">
    <div class="input-field col s8">
        <input id="detail" type="text" class="validate">
        <label for="detail">刘子</label>
    </div>
    <div class="col s4" id="c1">
        <a class="waves-effect waves-light btn" id="submit">提交</a>
    </div>
</div>
<table class="striped">
    <thead>
    <tr>
        <th data-field="id" id="date">日♂期</th>
        <th data-field="name">详情</th>
    </tr>
    </thead>

    <tbody id="tbb">


    </tbody>
</table>

</body>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>

<script src="https://cdn.bootcss.com/materialize/0.100.2/js/materialize.min.js"></script>
<script>
    function getData(order_by) {

        $.ajax({
            url: '/api/liuzi',
            dataType: "json",
            contentType: "application/json",
            async: false,
            data: {"q": JSON.stringify({"order_by": order_by})},
            success: function (data) {
                if (data["num_results"]) {
                    $("tr").remove(".tbr");
                    for (var i = 0; i < data["num_results"]; i++) {
                        var datas = data["objects"][i];
                        $("#tbb").append("<tr class=\"tbr\"> <td>" + datas["created_at"].split("T")[0] + "</td> <td>" + datas["detail"] + "</td>  </tr>")
                    }

                }
                else {

                }

            }

        })
    }
    function getNow() {
        var date = new Date();
        var seperator1 = "-";
        var month = date.getMonth() + 1;
        var strDate = date.getDate();
        if (month >= 1 && month <= 9) {
            month = "0" + month;
        }
        if (strDate >= 0 && strDate <= 9) {
            strDate = "0" + strDate;
        }
        return date.getFullYear() + seperator1 + month + seperator1 + strDate;
    }
    function setData(detail) {
        var postbody = {
            "created_at": getNow(),
            "detail": "刘子"+detail
        };
        $.ajax({
            url: '/api/liuzi',
            type: 'POST',
            dataType: "json",
            data: JSON.stringify(postbody),
            contentType: "application/json; charset=utf-8",
            processData: false,
            async: false,
            success: function (data) {
                getData({"field": "id", "direction": "desc"});
                alert("记录刘子研究生生活の点点滴滴");
            }

        })
    }
    $(document).ready(function () {
        var order = "desc";
        getData([{"field": "id", "direction": order}]);
        $("#submit").click(function () {
            if (!$("#detail").val()) {
                alert("刘子今天干了啥？");
                return;
            }
            setData($("#detail").val());
        });
        $("#date").click(function () {
            if (order === "desc") {
                order = "asc";

            }
            else {
                order = "desc";
            }
            getData([{"field": "id", "direction": order}]);
        })
    })
</script>
</html>

app/templates/game/space.html
{% extends "base.html" %}
{% block css %}

<title>生日宇宙</title>
{% endblock %}
{% block content %}
<img style="  max-height: 100%;max-width: 100%;  position: absolute;margin: auto;top: 0;left: 0;right: 0;bottom: 0;" src="http://q7xvmvmiv.bkt.clouddn.com/{{ space.img }}">
<div style="width: 100%;bottom: 15px;position: absolute;text-align: center;">
    <a href="#modal1" style="color: black;" class="modal-trigger">
        <p style="color: white">查看介绍</p>
    </a>
    <a href="{{ space.srcurl }}" style="color: black;">
        <p style="color: white">访问原网站</p>
    </a>
    <a href="{{ url_for('web.spaceSearch') }}" style="color: black;">
        <p style="color: white">回首页</p>
    </a>

</div>
  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
        <div style="width: 100%;text-align: left">
            <h5>{{ space.id|noZeroBefore }}</h5>
            <h5>{{ space.name }}</h5>
            <p>{{ space.description }}</p>
        </div>
    </div>
     <div class="modal-footer">
        <a href="http://q7xvmvmiv.bkt.clouddn.com/{{ space.img }}"  class=" waves-effect waves-green btn-flat">
        查看原图
        </a>
    </div>
  </div>
{% endblock %}
{% block script %}
<script>
  $(document).ready(function () {
        $("body").css("background-color","black");
        $('.modal').modal();
  });
</script>
{% endblock %}

app/templates/game/spacesearch.html
{% extends "base.html" %}
{% block css %}
<title>生日宇宙</title>
{% endblock %}
{% block content %}
<a href="https://www.nasa.gov/content/goddard/what-did-hubble-see-on-your-birthday">
  <div class="card teal lighten-4" style="margin-top: 0;padding: 5px">
    <div class="card-content black-text" style="padding: 12px">
      <p>
        哈勃望远镜在你生日当天拍摄了什么？创意&数据来源于
      </p>
      <p>
        https://www.nasa.gov/content/goddard/what-did-hubble-see-on-your-birthday
      </p>
      <p>
        点击访问原网站
      </p>
    </div>
  </div>
</a>
<div class="row" style="margin-top: 40px">
    <div class="col s1 m4 l4"></div>
    <div class="col s10 m4 l4 " style="text-align: center">
        <div class="input-field ">
          <input id="date" type="number" class="validate">
          <label for="date">输入日期</label>
          <span class="helper-text" data-error="wrong" data-success="right">如：0614</span>
        </div>
        <div style="margin-top: 10px"><a class="waves-effect waves-light btn" id="submit">提交</a></div>
    </div>

</div>

{% endblock %}
{% block script %}
<script>
  $(document).ready(function () {
    //$('.fixed-action-btn').floatingActionButton();
    $('.modal').modal();
    $("#submit").click(function () {
      var val = $("#date").val();
      window.location.href = "space/" + val;
    })
  });
</script>
{% endblock %}

app/templates/game/thanos.html
<!DOCTYPE html>
<html lang="en" style="height: 100%">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{{ url_for('static',filename='img/icon.ico') }}"/>
    <title>你能从灭霸手中幸存吗？</title>
</head>
<body style="height: 100%">

    <div style="height: 50%"></div>
 <div style="font-size: 5rem;text-align: center; padding: 30px;">{{ msg }}</div>
</body>
</html>